source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCShare' do
  pod 'LDSDKManager'
  pod 'MMPopupView'
  pod 'SDWebImage/GIF'
  pod 'SDVersion', git: 'https://github.com/cguess/SDVersion'
  pod 'MCStyle'
  pod 'MCBase'
  pod 'MCUIKit', git: 'https://github.com/poholo/MCUIKit'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end
