source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCShare' do
  pod 'LDSDKManager', git: 'https://github.com/poholo/LDSDKManager_IOS'
  pod 'MMPopupView'
  pod 'SDWebImage'
  pod 'SDVersion', git: 'https://github.com/cguess/SDVersion'
end
