source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MCShare' do
  pod 'LDSDKManager'
  pod 'MMPopupView'
  pod 'SDWebImage'
  pod 'SDVersion', git: 'https://github.com/cguess/SDVersion'
end
